export const EMOJI_GROUPS = [
  {
    name: "Common",
    symbols:
      "😂 🤣 😊 😍 🥰 😭 😎 😅 😁 🙂 🙃 😉 😘 🤗 🤔 😮 😢 🥹 🫶 ❤️ 💙 💜 💚 💛 🧡 🤍 🖤 💔 ❤️‍🔥 🙏 🙌 👍 👎 👏 👋 🤝 💪 🔥 ✨ 🎉 💯 ✅ 👀 🥳 😇 🕊️",
  },
  {
    name: "Faces",
    symbols:
      "😀 😃 😄 😆 😋 😛 😜 🤪 😝 🤑 🤭 🫢 🫣 🤫 🤨 😐 😑 😶 🫥 😏 😒 🙄 😬 😌 😔 😪 🤤 😴 😷 🤒 🤕 🤢 🤮 🤧 🥵 🥶 🥴 😵 🤯 🥸 😕 🫤 😟 🙁 ☹️ 😯 😲 😳 🥺 😦 😧 😨 😰 😥 😓 😩 😫 😤 😡 😠 🤬 😈 👿 💀 ☠️ 👻 🤖 😺 😸 😹 😻 😼 😽 🙀 😿 😾",
  },
  {
    name: "Hands",
    symbols:
      "🖐️ ✋ 🖖 🫱 🫲 🫳 🫴 ✌️ 🤞 🫰 🤟 🤘 🤙 👈 👉 👆 👇 ☝️ 🫵 ✊ 👊 🤛 🤜 🤚 👐 🤲 💅 ✍️ 👍🏻 👍🏼 👍🏽 👍🏾 👍🏿 🙏🏻 🙏🏼 🙏🏽 🙏🏾 🙏🏿 👋🏻 👋🏼 👋🏽 👋🏾 👋🏿 🫶🏻 🫶🏼 🫶🏽 🫶🏾 🫶🏿",
  },
  {
    name: "Love",
    symbols: "💕 💞 💓 💗 💖 💘 💝 💟 ❣️ ❤️‍🩹 🩷 🩵 🩶 💌 💋 🌹 🥀 🌷 🌺 🌸 🌼 🌻 💐 🧸 🎁 🎀 💍 🫂",
  },
  {
    name: "Faith",
    symbols: "✝️ 📖 🛐 ⛪ 🕯️ 🪔 🌅 🌄 🌈 🌟 ⭐ 💫 ☀️ 🌤️ 🌙 🕊️ 🙏 🙌 😇 🤲 🫶 💒 🎶 🎵 🎼 🎤 🎸 🎹",
  },
  {
    name: "Nature",
    symbols:
      "🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐨 🐯 🦁 🐮 🐷 🐸 🐵 🙈 🙉 🙊 🦋 🐝 🐢 🐬 🐳 🦅 🦉 🐣 🐥 🐧 🦆 🌍 🌎 🌏 🌊 🌴 🌳 🌿 🍀 🍃 🍂 🍁 🏔️ 🌋 🌠 🌌 ⚡ ❄️ ☔ 🌧️",
  },
  {
    name: "Food",
    symbols:
      "🍎 🍊 🍋 🍌 🍉 🍇 🍓 🫐 🍍 🥭 🥑 🥕 🌽 🥔 🥐 🍞 🥞 🧀 🍳 🍗 🍖 🍔 🍟 🍕 🌭 🥪 🌮 🌯 🍝 🍜 🍛 🍚 🍿 🍩 🍪 🎂 🍰 🧁 🍫 🍬 🍭 🍯 🥛 ☕ 🍵 🧃 🥤 🧋 💧",
  },
  {
    name: "Life",
    symbols:
      "⚽ 🏀 🏈 🎾 🏐 🏓 🏸 🏆 🥇 🥈 🥉 🎯 🎮 🎲 🧩 🎨 🎬 🎧 🥁 🪘 💃 🕺 🚶 🏃 🏋️ 🧘 🚴 🏊 🛌 🏠 🏫 🏥 🏢 🚗 🚕 🚌 🚲 🏍️ ✈️ 🚀 🚦 📱 💻 ⌨️ 📷 🎥 💡 📚 📝 ✏️ 📅 ⏰ 💰 💸 💼 🛍️ 🇰🇪",
  },
  {
    name: "Symbols",
    symbols:
      "❌ ❎ ✔️ ☑️ ➕ ➖ ➗ ✖️ ❓ ❔ ❗ ❕ ‼️ ⁉️ 💬 💭 🗨️ 🔔 🔕 📢 📣 🔒 🔓 🔑 🛡️ ⚠️ 🚫 ⛔ 🔴 🟠 🟡 🟢 🔵 🟣 ⚫ ⚪ 🟤 🔷 🔶 🔹 🔸 ◀️ ▶️ ⏸️ ⏹️ 🔁 🔄 🔗 📍 🏳️ 🏁",
  },
] as const;

const emojiNames: Record<string, string> = {
  "😂": "laugh tears joy funny",
  "🤣": "rolling laugh funny",
  "😊": "smile happy blush",
  "😍": "love heart eyes",
  "🥰": "love hearts",
  "😭": "cry tears sad",
  "😎": "cool sunglasses",
  "🙏": "pray please thanks thank you",
  "🙌": "praise celebrate hands",
  "👍": "thumbs up yes okay",
  "👎": "thumbs down no",
  "❤️": "red heart love",
  "💙": "blue heart love",
  "🤔": "think question",
  "🥹": "touched happy tears",
  "🫶": "heart hands love",
  "🔥": "fire hot lit",
  "🎉": "party celebrate congratulations",
  "💯": "hundred perfect",
  "✅": "check yes done",
  "🕊️": "dove peace faith",
  "🇰🇪": "Kenya flag",
  "☕": "coffee tea",
  "📖": "Bible book read",
  "👀": "eyes looking",
  "👋": "wave hello goodbye",
  "🤝": "handshake agreement",
  "👏": "clap applause",
  "😇": "angel blessed",
  "🥳": "party birthday",
  "💔": "broken heart sad",
  "✝️": "cross Christian Jesus",
  "⛪": "church worship",
  "🫂": "hug comfort",
  "💪": "strong strength",
  "🤗": "hug welcome",
  "😢": "cry sad",
  "😅": "laugh nervous sweat",
  "🙂": "smile happy",
  "🙃": "upside down smile",
  "😉": "wink",
  "😘": "kiss love",
  "💀": "skull dead funny",
  "✨": "sparkles shine",
  "🎂": "cake birthday",
  "🎁": "gift present",
  "🌹": "rose flower love",
  "😴": "sleep tired",
  "😡": "angry mad",
  "🥺": "pleading please",
  "😮": "surprise wow",
  "💃": "dance",
  "📱": "phone",
  "💻": "laptop computer",
  "⚽": "football soccer",
  "🎶": "music song",
  "🌅": "sunrise morning",
  "🌙": "moon night",
  "💚": "green heart love",
  "💛": "yellow heart love",
  "💜": "purple heart love",
  "🧡": "orange heart love",
  "🤍": "white heart love",
  "🖤": "black heart love",
};
export const EMOJIS = [...new Set(EMOJI_GROUPS.flatMap((group) => group.symbols.split(" ")))];
export function emojiMatches(symbol: string, category: string, query: string) {
  const needle = query.trim().toLocaleLowerCase();
  return (
    !needle ||
    `${symbol} ${category} ${emojiNames[symbol] || ""}`.toLocaleLowerCase().includes(needle)
  );
}

const packs = [
  {
    name: "Everyday",
    color: "#dbeafe",
    items: [
      ["👋", "Hey there!"],
      ["😊", "Good morning"],
      ["🌙", "Good night"],
      ["🤝", "Thank you!"],
      ["👍", "Got it!"],
      ["🫶", "You're welcome"],
      ["☕", "Coffee time"],
      ["👀", "I'm listening"],
      ["🏃", "On my way"],
      ["💬", "Let's talk"],
    ],
  },
  {
    name: "Reactions",
    color: "#fef3c7",
    items: [
      ["😂", "Too funny!"],
      ["🤣", "Can't stop laughing"],
      ["😮", "WOW!"],
      ["🔥", "That's fire!"],
      ["🤔", "Thinking…"],
      ["🙈", "Oops!"],
      ["😎", "So cool"],
      ["🥹", "Happy tears"],
      ["😅", "My bad"],
      ["🤯", "Mind blown"],
    ],
  },
  {
    name: "Faith",
    color: "#e0e7ff",
    items: [
      ["🙏", "Praying for you"],
      ["🙌", "Amen!"],
      ["✝️", "Jesus loves you"],
      ["📖", "Stay in the Word"],
      ["🕊️", "Peace be with you"],
      ["😇", "Stay blessed"],
      ["🌅", "New mercies"],
      ["🌟", "Let your light shine"],
      ["🎶", "Praise the Lord"],
      ["❤️", "God is faithful"],
    ],
  },
  {
    name: "Love",
    color: "#fce7f3",
    items: [
      ["❤️", "Sending love"],
      ["🫂", "Big hug"],
      ["🥰", "You're loved"],
      ["💙", "Here for you"],
      ["🌹", "For you"],
      ["🫶", "Love this!"],
      ["💖", "You matter"],
      ["💌", "Thinking of you"],
      ["🧸", "Take care"],
      ["💕", "Love you lots"],
    ],
  },
  {
    name: "Encourage",
    color: "#dcfce7",
    items: [
      ["💪", "You got this!"],
      ["🌱", "Keep growing"],
      ["✨", "Keep shining"],
      ["🏆", "Proud of you!"],
      ["🤲", "One day at a time"],
      ["🌈", "There is hope"],
      ["🛡️", "Stay strong"],
      ["🚀", "Keep going"],
      ["💯", "Believe in yourself"],
      ["🌻", "Better days ahead"],
    ],
  },
  {
    name: "Celebrate",
    color: "#ffedd5",
    items: [
      ["🎉", "Congratulations!"],
      ["🎂", "Happy birthday!"],
      ["👏", "Well done!"],
      ["🥳", "Let's celebrate"],
      ["🎓", "You did it!"],
      ["🥇", "Champion!"],
      ["🎁", "A little surprise"],
      ["🎊", "Big win!"],
      ["💃", "Happy dance"],
      ["⭐", "Superstar!"],
    ],
  },
  {
    name: "Feelings",
    color: "#ede9fe",
    items: [
      ["😴", "Need some rest"],
      ["🥺", "Please?"],
      ["😭", "Not okay today"],
      ["😤", "Deep breaths"],
      ["😌", "Feeling peaceful"],
      ["🤗", "So happy!"],
      ["😬", "Awkward…"],
      ["🥴", "What a day"],
      ["😔", "I'm sorry"],
      ["🤍", "Be gentle"],
    ],
  },
  {
    name: "Community",
    color: "#cffafe",
    items: [
      ["🇰🇪", "Karibu!"],
      ["🤝", "Tuko pamoja"],
      ["🙌", "Sawa sawa!"],
      ["💙", "Our Nuru family"],
      ["🎤", "Worship together"],
      ["📅", "See you there"],
      ["⛪", "Church time"],
      ["📚", "Study together"],
      ["👋", "Catch you later"],
      ["🕊️", "Peace & love"],
    ],
  },
  {
    name: "Swahili",
    color: "#ccfbf1",
    items: [
      ["👋", "Habari yako?"],
      ["😊", "Niko poa"],
      ["🙏", "Asante sana"],
      ["💙", "Nakupenda"],
      ["🤗", "Nimekumiss"],
      ["🙌", "Mungu ni mwema"],
      ["🕊️", "Mungu akubariki"],
      ["💪", "Usikate tamaa"],
      ["🤝", "Twende pamoja"],
      ["😄", "Karibu sana"],
      ["🎉", "Hongera sana!"],
      ["🌅", "Habari za asubuhi"],
      ["🌙", "Lala salama"],
      ["👍", "Sawa kabisa"],
      ["⏳", "Ngoja kidogo"],
      ["🏃", "Nakuja sasa"],
      ["😂", "Umenichekesha"],
      ["🍽️", "Umekula?"],
      ["📞", "Nipigie"],
      ["☀️", "Siku njema"],
    ],
  },
  {
    name: "Prayer",
    color: "#e0e7ff",
    items: [
      ["🙏", "Prayer time"],
      ["🤲", "Lord, guide me"],
      ["🕯️", "Remembering you in prayer"],
      ["💙", "God sees you"],
      ["🌅", "Grace for today"],
      ["✝️", "Saved by grace"],
      ["🙌", "Hallelujah!"],
      ["🕊️", "Rest in His peace"],
      ["📖", "Walk by faith"],
      ["🌱", "Trust His timing"],
      ["💪", "Strength for today"],
      ["❤️", "Loved beyond measure"],
      ["🌟", "God goes before you"],
      ["🤝", "Let us pray together"],
      ["🎶", "A heart of worship"],
      ["🌈", "Holding on to hope"],
      ["🛡️", "God is my refuge"],
      ["⛪", "See you at fellowship"],
      ["🤍", "Thank You, Lord"],
      ["✨", "All glory to God"],
    ],
  },
  {
    name: "Fun",
    color: "#fef3c7",
    items: [
      ["🍿", "Here for the story"],
      ["👀", "Tell me everything"],
      ["😂", "You made my day"],
      ["🙃", "Plot twist!"],
      ["🤭", "I cannot explain"],
      ["😎", "Main character moment"],
      ["🐢", "Taking it slowly"],
      ["🐧", "Just chilling"],
      ["🐸", "Just checking in"],
      ["🦁", "Feeling brave"],
      ["🐱", "Sending good vibes"],
      ["🐶", "Bestie energy"],
      ["🐼", "Hug delivery"],
      ["🦋", "Little joys"],
      ["☕", "Tea, please"],
      ["🍕", "Snack break"],
      ["💃", "Weekend mood"],
      ["🎮", "Game time"],
      ["🎧", "My favourite song"],
      ["🤯", "Wait, what?"],
    ],
  },
  {
    name: "Study",
    color: "#dbeafe",
    items: [
      ["📚", "Study mode"],
      ["💻", "Coding time"],
      ["📝", "Taking notes"],
      ["🎯", "Stay focused"],
      ["☕", "Revision break"],
      ["⏰", "Deadline approaching"],
      ["🤝", "We can do this together"],
      ["📖", "One more chapter"],
      ["🧠", "Learning something new"],
      ["💡", "I have an idea"],
      ["✅", "Assignment done"],
      ["🎓", "Exam day"],
      ["🙏", "Praying for your exams"],
      ["💪", "Keep practising"],
      ["🚀", "Making progress"],
      ["🌱", "Small steps count"],
      ["🥳", "Passed!"],
      ["😴", "Time to recharge"],
      ["📅", "See you in class"],
      ["🏆", "Hard work pays off"],
    ],
  },
  {
    name: "Youth",
    color: "#e0f2fe",
    items: [
      ["🔥", "Nuru vibes"],
      ["😎", "Big energy"],
      ["🫶", "You are my people"],
      ["😂", "That finished me"],
      ["👀", "I saw that"],
      ["🤭", "Say less"],
      ["💯", "No cap"],
      ["✨", "Main character energy"],
      ["🎧", "On repeat"],
      ["📱", "Text me back"],
      ["🧃", "Take a break"],
      ["🚀", "We move"],
      ["🌈", "Good vibes only"],
      ["🧠", "Brain loading"],
      ["🫠", "I am done"],
      ["😮‍💨", "Long day"],
      ["🪩", "Weekend loading"],
      ["📸", "Picture time"],
      ["🤝", "We are locked in"],
      ["🥹", "Too wholesome"],
    ],
  },
  {
    name: "Worship",
    color: "#ede9fe",
    items: [
      ["🙌", "Hands lifted"],
      ["🎤", "Sing it out"],
      ["🎶", "Worship mode"],
      ["🎹", "Keys and praise"],
      ["🥁", "Make a joyful noise"],
      ["🎸", "Praise louder"],
      ["🕊️", "Holy Spirit move"],
      ["🔥", "Set my heart on fire"],
      ["❤️", "Here is my heart"],
      ["🌅", "Morning worship"],
      ["🌙", "Night of worship"],
      ["⛪", "See you in church"],
      ["🙏", "Lead me Lord"],
      ["✨", "Your presence is enough"],
      ["👑", "King of Kings"],
      ["📖", "Your Word is life"],
      ["🤍", "Surrendered"],
      ["🌊", "Deep calls to deep"],
      ["💫", "Glory to God"],
      ["🎼", "One more song"],
    ],
  },
  {
    name: "Bible",
    color: "#fef9c3",
    items: [
      ["📖", "Open your Bible"],
      ["💡", "Word for today"],
      ["🧭", "His Word guides me"],
      ["🛡️", "Armor up"],
      ["🌱", "Rooted in the Word"],
      ["🕯️", "Light for my path"],
      ["⛰️", "Faith moves mountains"],
      ["🌊", "Peace be still"],
      ["🦁", "Be bold"],
      ["❤️", "Love never fails"],
      ["🤲", "Ask and receive"],
      ["🚪", "Knock and it will open"],
      ["🌟", "Shine your light"],
      ["🕊️", "Walk in peace"],
      ["🍞", "Daily bread"],
      ["💧", "Living water"],
      ["👣", "Follow Jesus"],
      ["🌿", "Abide in Him"],
      ["🏠", "Build on the rock"],
      ["👑", "Seek first the Kingdom"],
    ],
  },
  {
    name: "Friends",
    color: "#fae8ff",
    items: [
      ["🫂", "Bestie hug"],
      ["👋", "Hey bestie"],
      ["😂", "You always make me laugh"],
      ["🫶", "Glad you are here"],
      ["🤝", "I have got you"],
      ["💙", "Friends for real"],
      ["☕", "Catch up soon?"],
      ["📞", "Call me"],
      ["📸", "Memory unlocked"],
      ["🎉", "We did that!"],
      ["🙌", "Proud of us"],
      ["🤗", "Missed you"],
      ["🥹", "That means a lot"],
      ["💌", "Just checking on you"],
      ["🌻", "You make life brighter"],
      ["🚗", "Road trip?"],
      ["🍕", "Food date"],
      ["🎧", "Our song"],
      ["🌙", "Sleep well friend"],
      ["☀️", "Have a good day"],
    ],
  },
  {
    name: "Goals",
    color: "#dcfce7",
    items: [
      ["🎯", "Locked in"],
      ["🚀", "Level up"],
      ["🏆", "Keep winning"],
      ["💪", "Discipline over mood"],
      ["📈", "Progress is progress"],
      ["🧠", "Think bigger"],
      ["💼", "Work mode"],
      ["⏰", "Time to focus"],
      ["✅", "Task complete"],
      ["📝", "Plan it out"],
      ["💡", "Build the idea"],
      ["🌱", "Growth season"],
      ["🧱", "One brick at a time"],
      ["🏁", "Finish strong"],
      ["👣", "Keep moving"],
      ["🔥", "Stay hungry"],
      ["⭐", "Aim higher"],
      ["🤝", "Let us build"],
      ["🥇", "Go for excellence"],
      ["🙏", "Commit your plans to God"],
    ],
  },
  {
    name: "Events",
    color: "#ffedd5",
    items: [
      ["📅", "Save the date"],
      ["🎟️", "See you there"],
      ["📍", "Location sent"],
      ["⏰", "Do not be late"],
      ["🎤", "Mic check"],
      ["🎶", "Worship night"],
      ["🙌", "Youth night"],
      ["⛪", "Sunday service"],
      ["🧑‍🤝‍🧑", "Bring a friend"],
      ["📸", "Photo moment"],
      ["🎥", "We are live"],
      ["🔥", "It is happening"],
      ["🥳", "Event mode"],
      ["🚗", "On the way"],
      ["👋", "Welcome in"],
      ["🪑", "Save me a seat"],
      ["🍽️", "Food is ready"],
      ["🎁", "Surprise inside"],
      ["🙏", "Let us pray before we start"],
      ["✅", "Registered"],
    ],
  },
  {
    name: "Comfort",
    color: "#e0e7ff",
    items: [
      ["🫂", "I am here"],
      ["🤍", "You are not alone"],
      ["🙏", "I am praying with you"],
      ["🌧️", "It is okay to feel this"],
      ["🌈", "This season will pass"],
      ["🌱", "Healing takes time"],
      ["🕊️", "Breathe and rest"],
      ["☕", "Take it slowly"],
      ["💙", "Sending comfort"],
      ["🌙", "Rest tonight"],
      ["☀️", "Tomorrow is a new day"],
      ["🤲", "Grace for this moment"],
      ["💪", "You are stronger than you feel"],
      ["🧡", "Be kind to yourself"],
      ["📖", "Hold on to the Word"],
      ["🌊", "Peace over your heart"],
      ["🕯️", "A little light for you"],
      ["🌻", "Hope is still here"],
      ["👂", "I am listening"],
      ["💌", "Thinking of you today"],
    ],
  },
  {
    name: "Energy",
    color: "#fee2e2",
    items: [
      ["🔥", "Let us go!"],
      ["⚡", "Full energy"],
      ["🚀", "We are moving"],
      ["💥", "Big moment"],
      ["🙌", "Yes!"],
      ["💯", "Absolutely"],
      ["😤", "Locked in"],
      ["🏃", "Move move move"],
      ["🎉", "Turn up"],
      ["🥳", "Celebrate it"],
      ["🕺", "Dance break"],
      ["💃", "Good mood"],
      ["🎶", "Volume up"],
      ["👏", "Come on!"],
      ["⭐", "You are shining"],
      ["🏆", "Winner energy"],
      ["🚨", "Important!"],
      ["👑", "Own the moment"],
      ["🌟", "This is your time"],
      ["😎", "Too smooth"],
    ],
  },
] as const;
export type ChatSticker = { id: string; emoji: string; label: string; pack: string; color: string };
// IDs remain stable as packs grow; saved messages store the ID and a readable body.
export const STICKERS: ChatSticker[] = packs.flatMap((pack) =>
  pack.items.map(([emoji, label]) => ({
    id: `nuru:${pack.name.toLowerCase()}:${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    emoji,
    label,
    pack: pack.name,
    color: pack.color,
  })),
);
export const STICKER_PACKS = packs.map((pack) => pack.name);
export const STICKER_BY_ID = new Map(STICKERS.map((sticker) => [sticker.id, sticker]));
