export type PostMusicTrack = {
  id: string;
  title: string;
  artist: string;
  mood: string;
  url: string;
  duration: number;
};
export const POST_MUSIC: PostMusicTrack[] = [
  {
    id: "USUAN1400037",
    title: "Carefree",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Bright, Calming, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carefree.mp3",
    duration: 205,
  },
  {
    id: "USUAN1400011",
    title: "Monkeys Spinning Monkeys",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Bright, Humorous, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Monkeys%20Spinning%20Monkeys.mp3",
    duration: 125,
  },
  {
    id: "USUAN1100517",
    title: "Sunshine",
    artist: "Kevin MacLeod",
    mood: "Bright, Calming, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sunshine%20A.mp3",
    duration: 202,
  },
  {
    id: "USUAN1400054",
    title: "Life of Riley",
    artist: "Kevin MacLeod",
    mood: "Bright, Relaxed, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Life%20of%20Riley.mp3",
    duration: 235,
  },
  {
    id: "USUAN1100843",
    title: "Wallpaper",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Bright, Calming, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wallpaper.mp3",
    duration: 220,
  },
  {
    id: "USUAN1100772",
    title: "Sneaky Snitch",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Dark, Humorous, Mysterious",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sneaky%20Snitch.mp3",
    duration: 137,
  },
  {
    id: "USUAN1300033",
    title: "Clean Soul",
    artist: "Kevin MacLeod",
    mood: "Calming, Mysterious, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clean%20Soul.mp3",
    duration: 307,
  },
  {
    id: "USUAN2000005",
    title: "Moonlight Beach",
    artist: "Kevin MacLeod",
    mood: "Bright, Grooving, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Moonlight%20Beach.mp3",
    duration: 339,
  },
  {
    id: "USUAN1100844",
    title: "Cipher",
    artist: "Kevin MacLeod",
    mood: "Bright, Grooving, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cipher2.mp3",
    duration: 231,
  },
  {
    id: "USUAN1300046",
    title: "Dream Culture",
    artist: "Kevin MacLeod",
    mood: "Calming, Relaxed, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dream%20Culture.mp3",
    duration: 214,
  },
  {
    id: "USUAN1200076",
    title: "Easy Lemon",
    artist: "Kevin MacLeod",
    mood: "Bright, Calming, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Easy%20Lemon.mp3",
    duration: 126,
  },
  {
    id: "USUAN1100693",
    title: "Finding Movement",
    artist: "Kevin MacLeod",
    mood: "Calming, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Finding%20Movement.mp3",
    duration: 116,
  },
  {
    id: "USUAN1500081",
    title: "Garden Music",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Mystical",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Garden%20Music.mp3",
    duration: 2477,
  },
  {
    id: "USUAN1100207",
    title: "Heartwarming",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Bright, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Heartwarming.mp3",
    duration: 72,
  },
  {
    id: "USUAN2300003",
    title: "Morning",
    artist: "Kevin MacLeod",
    mood: "Bright, Calming, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Morning.mp3",
    duration: 153,
  },
  {
    id: "USUAN1200099",
    title: "Peace of Mind",
    artist: "Kevin MacLeod",
    mood: "Calming, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Peace%20of%20Mind.mp3",
    duration: 2158,
  },
  {
    id: "USUAN1100715",
    title: "Porch Swing Days - slower",
    artist: "Kevin MacLeod",
    mood: "Bright, Calming, Relaxed, Uplifting",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Porch%20Swing%20Days%20-%20slower.mp3",
    duration: 216,
  },
  {
    id: "USUAN1500075",
    title: "Relaxing Piano Music",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Relaxing%20Piano%20Music.mp3",
    duration: 1494,
  },
  {
    id: "USUAN1100080",
    title: "Shades of Spring",
    artist: "Kevin MacLeod",
    mood: "Dark, Bouncy",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Shades%20of%20Spring.mp3",
    duration: 187,
  },
  {
    id: "USUAN1500068",
    title: "The Show Must Be Go",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Humorous",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Show%20Must%20Be%20Go.mp3",
    duration: 216,
  },
  {
    id: "USUAN1500063",
    title: "Upbeat Forever",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Bright",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Upbeat%20Forever.mp3",
    duration: 195,
  },
  {
    id: "USUAN1900060",
    title: "A Very Brady Special",
    artist: "Kevin MacLeod",
    mood: "Calming, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/A%20Very%20Brady%20Special.mp3",
    duration: 388,
  },
  {
    id: "USUAN2500003",
    title: "Dentaneosuchus Hunt",
    artist: "Kevin MacLeod",
    mood: "Action, Driving, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dentaneosuchus%20Hunt.mp3",
    duration: 247,
  },
  {
    id: "USUAN2500002",
    title: "Sauropod Spotting",
    artist: "Kevin MacLeod",
    mood: "Action, Driving, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sauropod%20Spotting.mp3",
    duration: 225,
  },
  {
    id: "USUAN2500001",
    title: "Cretaceous Dawn",
    artist: "Kevin MacLeod",
    mood: "Action, Driving, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cretaceous%20Dawn.mp3",
    duration: 245,
  },
  {
    id: "USUAN2400001",
    title: "That Zen Moment",
    artist: "Kevin MacLeod",
    mood: "Calming, Mystical, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/That%20Zen%20Moment.mp3",
    duration: 602,
  },
  {
    id: "USUAN2300012",
    title: "Sergio's Magic Dustbin",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Driving, Humorous",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sergio%27s%20Magic%20Dustbin.mp3",
    duration: 151,
  },
  {
    id: "USUAN2300011",
    title: "Mesmerizing Galaxy",
    artist: "Kevin MacLeod",
    mood: "Grooving, Mysterious",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Mesmerizing%20Galaxy%20Loop.mp3",
    duration: 93,
  },
  {
    id: "USUAN2300010",
    title: "Lord of the Rangs",
    artist: "Kevin MacLeod",
    mood: "Grooving, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Lord%20of%20the%20Rangs.mp3",
    duration: 92,
  },
  {
    id: "USUAN2300009",
    title: "Galactic Rap",
    artist: "Kevin MacLeod",
    mood: "Grooving, Mysterious, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Galactic%20Rap.mp3",
    duration: 142,
  },
  {
    id: "USUAN2300008",
    title: "Equatorial Complex",
    artist: "Kevin MacLeod",
    mood: "Bright, Mystical, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Equatorial%20Complex.mp3",
    duration: 240,
  },
  {
    id: "USUAN2300007",
    title: "Cloud Dancer",
    artist: "Kevin MacLeod",
    mood: "Grooving, Bouncy, Bright",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cloud%20Dancer.mp3",
    duration: 220,
  },
  {
    id: "USUAN2300006",
    title: "Brain Dance",
    artist: "Kevin MacLeod",
    mood: "Grooving, Driving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brain%20Dance.mp3",
    duration: 215,
  },
  {
    id: "USUAN2300005",
    title: "Vibing Over Venus",
    artist: "Kevin MacLeod",
    mood: "Calming, Grooving, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Vibing%20Over%20Venus.mp3",
    duration: 411,
  },
  {
    id: "USUAN2300004",
    title: "Southern Gothic",
    artist: "Kevin MacLeod",
    mood: "Dark, Grooving, Mysterious",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Southern%20Gothic.mp3",
    duration: 147,
  },
  {
    id: "USUAN2300002",
    title: "Evening",
    artist: "Kevin MacLeod",
    mood: "Bright, Calming, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Evening.mp3",
    duration: 186,
  },
  {
    id: "USUAN2300001",
    title: "Goblin Tinker Soldier Spy",
    artist: "Kevin MacLeod",
    mood: "Grooving, Bouncy, Humorous",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Goblin_Tinker_Soldier_Spy.mp3",
    duration: 136,
  },
  {
    id: "USUAN2300000",
    title: "Paradise Found",
    artist: "Kevin MacLeod",
    mood: "Bright, Grooving, Bouncy",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Paradise_Found.mp3",
    duration: 187,
  },
  {
    id: "USUAN2200005",
    title: "Magic Escape Room",
    artist: "Kevin MacLeod",
    mood: "Driving, Grooving, Bouncy",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Magic%20Escape%20Room.mp3",
    duration: 863,
  },
  {
    id: "USUAN2200004",
    title: "I Got a Stick Arr Bryan Teoh",
    artist: "Kevin MacLeod",
    mood: "Driving, Grooving, Bouncy",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Got%20a%20Stick%20Arr%20Bryan%20Teoh.mp3",
    duration: 31,
  },
  {
    id: "USUAN2200003",
    title: "I Got a Stick Feat James Gavins",
    artist: "Kevin MacLeod",
    mood: "Driving, Grooving, Bouncy",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Got%20a%20Stick%20Feat%20James%20Gavins.mp3",
    duration: 31,
  },
  {
    id: "USUAN2200002",
    title: "Boogie Party",
    artist: "Kevin MacLeod",
    mood: "Driving, Grooving, Bouncy",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Boogie%20Party.mp3",
    duration: 272,
  },
  {
    id: "USUAN2200001",
    title: "Journey To Ascend",
    artist: "Kevin MacLeod",
    mood: "Driving, Grooving, Mystical",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Journey%20To%20Ascend.mp3",
    duration: 219,
  },
  {
    id: "USUAN2100031",
    title: "Ethereal Relaxation",
    artist: "Kevin MacLeod",
    mood: "Bright, Relaxed, Calming",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ethereal%20Relaxation.mp3",
    duration: 1686,
  },
  {
    id: "USUAN2100030",
    title: "Space Jazz",
    artist: "Kevin MacLeod",
    mood: "Bright, Grooving, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Space%20Jazz.mp3",
    duration: 370,
  },
  {
    id: "USUAN2100029",
    title: "Adventures in Adventureland",
    artist: "Kevin MacLeod",
    mood: "Action, Bright, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Adventures%20in%20Adventureland.mp3",
    duration: 261,
  },
  {
    id: "USUAN2100028",
    title: "Fox Tale Waltz Part 1",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Bright, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fox%20Tale%20Waltz%20Part%201.mp3",
    duration: 429,
  },
  {
    id: "USUAN2100027",
    title: "Grand Dark Waltz Trio Vivace",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Trio%20Vivace.mp3",
    duration: 172,
  },
  {
    id: "USUAN2100026",
    title: "Grand Dark Waltz Trio Allegro",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Trio%20Allegro.mp3",
    duration: 195,
  },
  {
    id: "USUAN2100025",
    title: "Fox Tale Waltz Part 1 Instrumental",
    artist: "Kevin MacLeod",
    mood: "Bouncy, Bright, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fox%20Tale%20Waltz%20Part%201%20Instrumental.mp3",
    duration: 429,
  },
  {
    id: "USUAN2100024",
    title: "Starting Out Waltz Vivace",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Starting%20Out%20Waltz%20Vivace.mp3",
    duration: 175,
  },
  {
    id: "USUAN2100023",
    title: "Starting Out Waltz Allegretto",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Starting%20Out%20Waltz%20Allegretto.mp3",
    duration: 249,
  },
  {
    id: "USUAN2100022",
    title: "Adeste Fideles (Shorter)",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Adeste%20Fideles%20Shorter.mp3",
    duration: 85,
  },
  {
    id: "USUAN2100021",
    title: "Adeste Fideles Waltz",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Adeste%20Fideles%20Waltz.mp3",
    duration: 140,
  },
  {
    id: "USUAN2100020",
    title: "Grand Dark Waltz Allegro",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Allegro.mp3",
    duration: 385,
  },
  {
    id: "USUAN2100019",
    title: "Grand Dark Waltz Allegretto",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Allegretto.mp3",
    duration: 450,
  },
  {
    id: "USUAN2100018",
    title: "Grand Dark Waltz Moderato",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Grand%20Dark%20Waltz%20Moderato.mp3",
    duration: 508,
  },
  {
    id: "USUAN2100017",
    title: "Devonshire Waltz Allegretto",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Devonshire%20Waltz%20Allegretto.mp3",
    duration: 313,
  },
  {
    id: "USUAN2100016",
    title: "Devonshire Waltz Moderato",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Devonshire%20Waltz%20Moderato.mp3",
    duration: 351,
  },
  {
    id: "USUAN2100015",
    title: "Devonshire Waltz Andante",
    artist: "Kevin MacLeod",
    mood: "Relaxed, Calming, Grooving",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Devonshire%20Waltz%20Andante.mp3",
    duration: 388,
  },
  {
    id: "USUAN2100014",
    title: "Joey's Formal Waltz - Unscented",
    artist: "Kevin MacLeod",
    mood: "Grooving, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Joey%27s%20Formal%20Waltz%20-%20Unscented.mp3",
    duration: 301,
  },
  {
    id: "USUAN2100013",
    title: "Joey's Formal Waltz - Scented",
    artist: "Kevin MacLeod",
    mood: "Calming, Grooving, Humorous",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Joey%2527s%20Formal%20Waltz.mp3",
    duration: 301,
  },
  {
    id: "USUAN2100012",
    title: "Valse Gymnopedie",
    artist: "Kevin MacLeod",
    mood: "Grooving, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Valse%20Gymnopedie.mp3",
    duration: 192,
  },
  {
    id: "USUAN2100011",
    title: "Funky Boxstep",
    artist: "Kevin MacLeod",
    mood: "Grooving, Relaxed",
    url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Funky%20Boxstep%20.mp3",
    duration: 316,
  },
];
export const POST_MUSIC_BY_ID = new Map(POST_MUSIC.map((track) => [track.id, track]));
