/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedBibleRouteImport } from './routes/_authenticated/bible'
import { Route as AuthenticatedChurchRouteImport } from './routes/_authenticated/church'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedDevotionalsRouteImport } from './routes/_authenticated/devotionals'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedFaithCoursesIndexRouteImport } from './routes/_authenticated/faith-courses.index'
import { Route as AuthenticatedFaithCoursesSlugRouteImport } from './routes/_authenticated/faith-courses.$slug'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedGrowRouteImport } from './routes/_authenticated/grow'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMusicRouteImport } from './routes/_authenticated/music'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPodcastsRouteImport } from './routes/_authenticated/podcasts'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedServeRouteImport } from './routes/_authenticated/serve'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMentorsIndexRouteImport } from './routes/_authenticated/mentors.index'
import { Route as AuthenticatedMentorsIdRouteImport } from './routes/_authenticated/mentors.$id'
import { Route as AuthenticatedSeriesIndexRouteImport } from './routes/_authenticated/series.index'
import { Route as AuthenticatedDiscoveryKindIdRouteImport } from './routes/_authenticated/discovery.$kind.$id'
import { Route as AuthenticatedSeriesSlugIndexRouteImport } from './routes/_authenticated/series.$slug.index'
import { Route as AuthenticatedSeriesSlugPositionRouteImport } from './routes/_authenticated/series.$slug.$position'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibleRoute = AuthenticatedBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChurchRoute = AuthenticatedChurchRouteImport.update({
  id: '/church',
  path: '/church',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevotionalsRoute =
  AuthenticatedDevotionalsRouteImport.update({
    id: '/devotionals',
    path: '/devotionals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaithCoursesIndexRoute =
  AuthenticatedFaithCoursesIndexRouteImport.update({
    id: '/faith-courses/',
    path: '/faith-courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaithCoursesSlugRoute =
  AuthenticatedFaithCoursesSlugRouteImport.update({
    id: '/faith-courses/$slug',
    path: '/faith-courses/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrowRoute = AuthenticatedGrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicRoute = AuthenticatedMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPodcastsRoute = AuthenticatedPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServeRoute = AuthenticatedServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorsIndexRoute =
  AuthenticatedMentorsIndexRouteImport.update({
    id: '/mentors/',
    path: '/mentors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorsIdRoute = AuthenticatedMentorsIdRouteImport.update({
  id: '/mentors/$id',
  path: '/mentors/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeriesIndexRoute =
  AuthenticatedSeriesIndexRouteImport.update({
    id: '/series/',
    path: '/series/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscoveryKindIdRoute =
  AuthenticatedDiscoveryKindIdRouteImport.update({
    id: '/discovery/$kind/$id',
    path: '/discovery/$kind/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeriesSlugIndexRoute =
  AuthenticatedSeriesSlugIndexRouteImport.update({
    id: '/series/$slug/',
    path: '/series/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeriesSlugPositionRoute =
  AuthenticatedSeriesSlugPositionRouteImport.update({
    id: '/series/$slug/$position',
    path: '/series/$slug/$position',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/bible': typeof AuthenticatedBibleRoute
  '/church': typeof AuthenticatedChurchRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/create': typeof AuthenticatedCreateRoute
  '/devotionals': typeof AuthenticatedDevotionalsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/faith-courses/': typeof AuthenticatedFaithCoursesIndexRoute
  '/faith-courses/$slug': typeof AuthenticatedFaithCoursesSlugRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/grow': typeof AuthenticatedGrowRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hub': typeof AuthenticatedHubRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/music': typeof AuthenticatedMusicRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/podcasts': typeof AuthenticatedPodcastsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/serve': typeof AuthenticatedServeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/mentors/$id': typeof AuthenticatedMentorsIdRoute
  '/mentors/': typeof AuthenticatedMentorsIndexRoute
  '/series/': typeof AuthenticatedSeriesIndexRoute
  '/discovery/$kind/$id': typeof AuthenticatedDiscoveryKindIdRoute
  '/series/$slug/$position': typeof AuthenticatedSeriesSlugPositionRoute
  '/series/$slug/': typeof AuthenticatedSeriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/bible': typeof AuthenticatedBibleRoute
  '/church': typeof AuthenticatedChurchRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/create': typeof AuthenticatedCreateRoute
  '/devotionals': typeof AuthenticatedDevotionalsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/faith-courses': typeof AuthenticatedFaithCoursesIndexRoute
  '/faith-courses/$slug': typeof AuthenticatedFaithCoursesSlugRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/grow': typeof AuthenticatedGrowRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hub': typeof AuthenticatedHubRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/music': typeof AuthenticatedMusicRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/podcasts': typeof AuthenticatedPodcastsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/serve': typeof AuthenticatedServeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/mentors/$id': typeof AuthenticatedMentorsIdRoute
  '/mentors': typeof AuthenticatedMentorsIndexRoute
  '/series': typeof AuthenticatedSeriesIndexRoute
  '/discovery/$kind/$id': typeof AuthenticatedDiscoveryKindIdRoute
  '/series/$slug/$position': typeof AuthenticatedSeriesSlugPositionRoute
  '/series/$slug': typeof AuthenticatedSeriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/bible': typeof AuthenticatedBibleRoute
  '/_authenticated/church': typeof AuthenticatedChurchRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/devotionals': typeof AuthenticatedDevotionalsRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/faith-courses/': typeof AuthenticatedFaithCoursesIndexRoute
  '/_authenticated/faith-courses/$slug': typeof AuthenticatedFaithCoursesSlugRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/grow': typeof AuthenticatedGrowRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/music': typeof AuthenticatedMusicRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/podcasts': typeof AuthenticatedPodcastsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/serve': typeof AuthenticatedServeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/mentors/$id': typeof AuthenticatedMentorsIdRoute
  '/_authenticated/mentors/': typeof AuthenticatedMentorsIndexRoute
  '/_authenticated/series/': typeof AuthenticatedSeriesIndexRoute
  '/_authenticated/discovery/$kind/$id': typeof AuthenticatedDiscoveryKindIdRoute
  '/_authenticated/series/$slug/$position': typeof AuthenticatedSeriesSlugPositionRoute
  '/_authenticated/series/$slug/': typeof AuthenticatedSeriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/reset-password'
    | '/welcome'
    | '/admin'
    | '/ai'
    | '/bible'
    | '/church'
    | '/community'
    | '/create'
    | '/devotionals'
    | '/events'
    | '/faith-courses/'
    | '/faith-courses/$slug'
    | '/explore'
    | '/groups'
    | '/grow'
    | '/home'
    | '/hub'
    | '/messages'
    | '/music'
    | '/notifications'
    | '/onboarding'
    | '/podcasts'
    | '/profile'
    | '/reels'
    | '/serve'
    | '/settings'
    | '/mentors/$id'
    | '/mentors/'
    | '/series/'
    | '/discovery/$kind/$id'
    | '/series/$slug/$position'
    | '/series/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/reset-password'
    | '/welcome'
    | '/admin'
    | '/ai'
    | '/bible'
    | '/church'
    | '/community'
    | '/create'
    | '/devotionals'
    | '/events'
    | '/faith-courses'
    | '/faith-courses/$slug'
    | '/explore'
    | '/groups'
    | '/grow'
    | '/home'
    | '/hub'
    | '/messages'
    | '/music'
    | '/notifications'
    | '/onboarding'
    | '/podcasts'
    | '/profile'
    | '/reels'
    | '/serve'
    | '/settings'
    | '/mentors/$id'
    | '/mentors'
    | '/series'
    | '/discovery/$kind/$id'
    | '/series/$slug/$position'
    | '/series/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/reset-password'
    | '/welcome'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/bible'
    | '/_authenticated/church'
    | '/_authenticated/community'
    | '/_authenticated/create'
    | '/_authenticated/devotionals'
    | '/_authenticated/events'
    | '/_authenticated/faith-courses/'
    | '/_authenticated/faith-courses/$slug'
    | '/_authenticated/explore'
    | '/_authenticated/groups'
    | '/_authenticated/grow'
    | '/_authenticated/home'
    | '/_authenticated/hub'
    | '/_authenticated/messages'
    | '/_authenticated/music'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/podcasts'
    | '/_authenticated/profile'
    | '/_authenticated/reels'
    | '/_authenticated/serve'
    | '/_authenticated/settings'
    | '/_authenticated/mentors/$id'
    | '/_authenticated/mentors/'
    | '/_authenticated/series/'
    | '/_authenticated/discovery/$kind/$id'
    | '/_authenticated/series/$slug/$position'
    | '/_authenticated/series/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bible': {
      id: '/_authenticated/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof AuthenticatedBibleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/church': {
      id: '/_authenticated/church'
      path: '/church'
      fullPath: '/church'
      preLoaderRoute: typeof AuthenticatedChurchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devotionals': {
      id: '/_authenticated/devotionals'
      path: '/devotionals'
      fullPath: '/devotionals'
      preLoaderRoute: typeof AuthenticatedDevotionalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faith-courses/': {
      id: '/_authenticated/faith-courses/'
      path: '/faith-courses'
      fullPath: '/faith-courses/'
      preLoaderRoute: typeof AuthenticatedFaithCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faith-courses/$slug': {
      id: '/_authenticated/faith-courses/$slug'
      path: '/faith-courses/$slug'
      fullPath: '/faith-courses/$slug'
      preLoaderRoute: typeof AuthenticatedFaithCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grow': {
      id: '/_authenticated/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof AuthenticatedGrowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music': {
      id: '/_authenticated/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AuthenticatedMusicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/podcasts': {
      id: '/_authenticated/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof AuthenticatedPodcastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/serve': {
      id: '/_authenticated/serve'
      path: '/serve'
      fullPath: '/serve'
      preLoaderRoute: typeof AuthenticatedServeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentors/': {
      id: '/_authenticated/mentors/'
      path: '/mentors'
      fullPath: '/mentors/'
      preLoaderRoute: typeof AuthenticatedMentorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentors/$id': {
      id: '/_authenticated/mentors/$id'
      path: '/mentors/$id'
      fullPath: '/mentors/$id'
      preLoaderRoute: typeof AuthenticatedMentorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series/': {
      id: '/_authenticated/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof AuthenticatedSeriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discovery/$kind/$id': {
      id: '/_authenticated/discovery/$kind/$id'
      path: '/discovery/$kind/$id'
      fullPath: '/discovery/$kind/$id'
      preLoaderRoute: typeof AuthenticatedDiscoveryKindIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series/$slug/': {
      id: '/_authenticated/series/$slug/'
      path: '/series/$slug'
      fullPath: '/series/$slug/'
      preLoaderRoute: typeof AuthenticatedSeriesSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series/$slug/$position': {
      id: '/_authenticated/series/$slug/$position'
      path: '/series/$slug/$position'
      fullPath: '/series/$slug/$position'
      preLoaderRoute: typeof AuthenticatedSeriesSlugPositionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBibleRoute: typeof AuthenticatedBibleRoute
  AuthenticatedChurchRoute: typeof AuthenticatedChurchRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDevotionalsRoute: typeof AuthenticatedDevotionalsRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFaithCoursesIndexRoute: typeof AuthenticatedFaithCoursesIndexRoute
  AuthenticatedFaithCoursesSlugRoute: typeof AuthenticatedFaithCoursesSlugRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedGrowRoute: typeof AuthenticatedGrowRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMusicRoute: typeof AuthenticatedMusicRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPodcastsRoute: typeof AuthenticatedPodcastsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedServeRoute: typeof AuthenticatedServeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMentorsIdRoute: typeof AuthenticatedMentorsIdRoute
  AuthenticatedMentorsIndexRoute: typeof AuthenticatedMentorsIndexRoute
  AuthenticatedSeriesIndexRoute: typeof AuthenticatedSeriesIndexRoute
  AuthenticatedDiscoveryKindIdRoute: typeof AuthenticatedDiscoveryKindIdRoute
  AuthenticatedSeriesSlugPositionRoute: typeof AuthenticatedSeriesSlugPositionRoute
  AuthenticatedSeriesSlugIndexRoute: typeof AuthenticatedSeriesSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBibleRoute: AuthenticatedBibleRoute,
  AuthenticatedChurchRoute: AuthenticatedChurchRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDevotionalsRoute: AuthenticatedDevotionalsRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFaithCoursesIndexRoute: AuthenticatedFaithCoursesIndexRoute,
  AuthenticatedFaithCoursesSlugRoute: AuthenticatedFaithCoursesSlugRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedGrowRoute: AuthenticatedGrowRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMusicRoute: AuthenticatedMusicRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPodcastsRoute: AuthenticatedPodcastsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedServeRoute: AuthenticatedServeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMentorsIdRoute: AuthenticatedMentorsIdRoute,
  AuthenticatedMentorsIndexRoute: AuthenticatedMentorsIndexRoute,
  AuthenticatedSeriesIndexRoute: AuthenticatedSeriesIndexRoute,
  AuthenticatedDiscoveryKindIdRoute: AuthenticatedDiscoveryKindIdRoute,
  AuthenticatedSeriesSlugPositionRoute: AuthenticatedSeriesSlugPositionRoute,
  AuthenticatedSeriesSlugIndexRoute: AuthenticatedSeriesSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
