alter table public.direct_messages
  add column if not exists message_type text not null default 'text',
  add column if not exists attachment_path text,
  add column if not exists attachment_duration_ms integer,
  add column if not exists sticker_code text,
  add column if not exists delivered_at timestamptz,
  add column if not exists read_at timestamptz;

alter table public.direct_messages
  drop constraint if exists direct_messages_message_type_check,
  add constraint direct_messages_message_type_check
    check (message_type in ('text','voice','sticker'));

alter table public.direct_messages
  drop constraint if exists direct_messages_attachment_duration_check,
  add constraint direct_messages_attachment_duration_check
    check (attachment_duration_ms is null or attachment_duration_ms between 0 and 600000);

alter table public.group_chat_messages
  add column if not exists message_type text not null default 'text',
  add column if not exists attachment_path text,
  add column if not exists attachment_duration_ms integer,
  add column if not exists sticker_code text;

alter table public.group_chat_messages
  drop constraint if exists group_chat_messages_message_type_check,
  add constraint group_chat_messages_message_type_check
    check (message_type in ('text','voice','sticker'));

alter table public.group_chat_messages
  drop constraint if exists group_chat_messages_attachment_duration_check,
  add constraint group_chat_messages_attachment_duration_check
    check (attachment_duration_ms is null or attachment_duration_ms between 0 and 600000);

grant update (delivered_at, read_at) on public.direct_messages to authenticated;

drop policy if exists "direct message recipient updates receipts" on public.direct_messages;
create policy "direct message recipient updates receipts"
on public.direct_messages
for update
to authenticated
using ((select auth.uid()) = recipient_id)
with check ((select auth.uid()) = recipient_id);

create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  caller_id uuid not null references auth.users(id) on delete cascade,
  callee_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('audio','video')),
  status text not null default 'ringing' check (status in ('ringing','active','declined','ended','missed')),
  offer jsonb not null,
  answer jsonb,
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  constraint call_sessions_not_self check (caller_id <> callee_id)
);

create index if not exists call_sessions_callee_status_created
  on public.call_sessions (callee_id, status, created_at desc);

create index if not exists call_sessions_caller_created
  on public.call_sessions (caller_id, created_at desc);

alter table public.call_sessions enable row level security;
revoke all on public.call_sessions from anon;
grant select, insert on public.call_sessions to authenticated;
grant update (status, answer, answered_at, ended_at) on public.call_sessions to authenticated;

drop policy if exists "call participants read" on public.call_sessions;
create policy "call participants read"
on public.call_sessions for select
to authenticated
using (
  (select auth.uid()) = caller_id
  or (select auth.uid()) = callee_id
);

drop policy if exists "caller creates call" on public.call_sessions;
create policy "caller creates call"
on public.call_sessions for insert
to authenticated
with check (
  (select auth.uid()) = caller_id
  and caller_id <> callee_id
);

drop policy if exists "call participants update" on public.call_sessions;
create policy "call participants update"
on public.call_sessions for update
to authenticated
using (
  (select auth.uid()) = caller_id
  or (select auth.uid()) = callee_id
)
with check (
  (select auth.uid()) = caller_id
  or (select auth.uid()) = callee_id
);

create table if not exists public.call_ice_candidates (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.call_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  candidate jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists call_ice_candidates_call_created
  on public.call_ice_candidates (call_id, created_at, id);

alter table public.call_ice_candidates enable row level security;
revoke all on public.call_ice_candidates from anon;
grant select, insert on public.call_ice_candidates to authenticated;

drop policy if exists "call candidates participants read" on public.call_ice_candidates;
create policy "call candidates participants read"
on public.call_ice_candidates for select
to authenticated
using (
  exists (
    select 1
    from public.call_sessions c
    where c.id = call_ice_candidates.call_id
      and ((select auth.uid()) = c.caller_id or (select auth.uid()) = c.callee_id)
  )
);

drop policy if exists "call candidates participant insert" on public.call_ice_candidates;
create policy "call candidates participant insert"
on public.call_ice_candidates for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.call_sessions c
    where c.id = call_ice_candidates.call_id
      and ((select auth.uid()) = c.caller_id or (select auth.uid()) = c.callee_id)
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'chat-media',
  'chat-media',
  false,
  15728640,
  array['audio/webm','audio/ogg','audio/mp4','audio/mpeg','audio/aac','audio/wav']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "chat media read participants" on storage.objects;
create policy "chat media read participants"
on storage.objects for select
to authenticated
using (
  bucket_id = 'chat-media'
  and (
    (
      (storage.foldername(name))[1] = 'direct'
      and (
        (storage.foldername(name))[2] = (select auth.uid())::text
        or (storage.foldername(name))[3] = (select auth.uid())::text
      )
    )
    or
    (
      (storage.foldername(name))[1] = 'group'
      and case
        when (storage.foldername(name))[2] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then private.is_group_member((select auth.uid()), ((storage.foldername(name))[2])::uuid)
        else false
      end
    )
  )
);

drop policy if exists "chat media upload sender" on storage.objects;
create policy "chat media upload sender"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'chat-media'
  and (
    (
      (storage.foldername(name))[1] = 'direct'
      and (storage.foldername(name))[2] = (select auth.uid())::text
    )
    or
    (
      (storage.foldername(name))[1] = 'group'
      and (storage.foldername(name))[3] = (select auth.uid())::text
      and case
        when (storage.foldername(name))[2] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then private.is_group_member((select auth.uid()), ((storage.foldername(name))[2])::uuid)
        else false
      end
    )
  )
);

drop policy if exists "chat media delete sender" on storage.objects;
create policy "chat media delete sender"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'chat-media'
  and (
    (
      (storage.foldername(name))[1] = 'direct'
      and (storage.foldername(name))[2] = (select auth.uid())::text
    )
    or
    (
      (storage.foldername(name))[1] = 'group'
      and (storage.foldername(name))[3] = (select auth.uid())::text
    )
  )
);
